version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 321
      MYSQL_USER: steam_user
      MYSQL_PASSWORD: 123
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./data/script:/docker-entrypoint-initdb.d

volumes:
  mysql-volume:
    driver: local
