version: '3.8'

services:
  db:
    image: mysql:8.0.32
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 321
      MYSQL_USER: steam_user
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: steam
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    command: '--skip-grant-tables'

volumes:
  mysql-volume:
    driver: local
